/*
 * This source file was generated by the Gradle 'init' task
 */
package prenotrist;


public class App {


    public static void main(String[] args) {
        Ristorante r = new Ristorante("Mimmo", 2,2,2,4,4,6,6,6);
        
        System.out.println(r.toString());

        r.gestore.prenotaTavolo("carlo", 4, r.tavoliDisponibili);
        System.out.println(r.toString());
        r.gestore.prenotaTavolo("stefano", 2, r.tavoliDisponibili);
        System.out.println(r.toString());
        r.gestore.cancellaPrenotazione("carlo", r.tavoliDisponibili);
        System.out.println(r.toString());
        
    }
}
